# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0005_subsystem_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subsystem_Info',
        ),
    ]
